### PR TITLE
Fix redirected and broken links

### PR DESCRIPTION
**Pull request by apjanke**
Fix redirected and broken links.

Fixes https://github.com/realpython/python-guide/issues/928.

### CODE REVIEW

**Comment by mpoulin** [comment]
Great work @apjanke !
Minor typo: change httph to https
`Crash into Python <httph://stephensugden.com/crash_into_python/>`_

**Comment by apjanke** [comment]
Oops! Thanks for catching that. Fixed.

**Comment by dbader** [comment]
Whoops looks like this has gone stale now—do you mind rebasing this/bringing in the latest changes from master so this PR merges cleanly?

**Comment by apjanke** [comment]
Rebased and merged in latest changes. Sorry for the slow response.

**Pull request merged**
