### PR TITLE
Fixed all H2 headings

### PR DESCRIPTION
**Pull request by mpoulin**
Before, H2 formatting was not consistent.
Now, all H2 headings use over/under asterisks.

### CODE REVIEW

**Comment by dbader** [comment]
@mpoulin Thanks so much Marc, this is great! Hurray for consistency 😄

**Comment by return42** [comment]
Sorry for nitpicking; If we change so many headings why not all and using recommended style for [sections and subsections](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html?highlight=heading#sections)

**Comment by mpoulin** [comment]
@return42 Thanks for your comment. 
Yes, the goal is to change all the headings to the recommended Sphinx style. 

A prior commit fixed the H1 headings:
693c8ca6773124afadf32c89a513aee03986a225

This commit fixes the H2 headings and the next commit will fix the H3 headings.
Since these are global changes and touch so many files, I thought it best to make the changes in phases.

**Comment by return42** [comment]
@mpoulin thanks for clarifying .

**Pull request merged**
