### PR TITLE
[fix search website] Changing the position of the script (not included)

### LINKED ISSUE #932: [doc website] Add nice search experience
👋 team,

I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [Bootstrap](https://getbootstrap.com/), [ESLint](https://eslint.org/) or [Babel](https://babeljs.io/).

We put together [a demo](https://python-guide-docsearch.surge.sh/) of what DocSearch on the python-guide website could look like here. Feel free to try it and let us know what you think. Please not the learn-as-you-type experience and the typo tolerance:

[demo of DocSearch + python-guide](https://python-guide-docsearch.surge.sh/)

The way DocSearch works is by crawling your content, pushing the results into an Algolia index, and then requesting this index directly from the website front-end through JavaScript.

We'll take care of crawling your website and populating the Algolia index with the latest changes every 24h for you. You don't need to change anything to your deployment process. The only thing you need to add are the following CSS and JS snippets that will bind the dropdown to your searchbox.

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '512b0d6c0c8578bed7662f5279c2249c',
  indexName: 'python-guide',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

The `inputSelector` option should be set to a CSS selector that target your search input. Feel free to update it if this one is not specific enough.

We built DocSearch with the idea of giving back to the Open-Source community. This is why your [crawling configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/python-guide.json) is available on GitHub if you want to change it. We also have our own [documentation](https://community.algolia.com/docsearch/documentation/) to help you tweak the dropdown to your needs. You'll also have access to *analytics on the most searched terms* or those with *no results*. All of this is of course *entirely free*.

Would that be something you'd be interested in? If so, we'd be happy to work on integrating it through a PR.

### PR DESCRIPTION
**Pull request by s-pace**
#933 fixed
#932

cc @dbader

### CODE REVIEW

**Comment by dbader** [comment]
@s-pace Cool—can you change the placeholder on the search input to "Search the Guide"? Then we're ready to go I think!

**Comment by dbader** [comment]
And ideally the search input should take up 100% of the navbar width to match the rest of the content there.

**Comment by dbader** [comment]
Got some issue with the styles now:

screenshot 2018-11-07 09 17 04

**Comment by s-pace** [comment]
I will inject the css in the same file.

**Comment by s-pace** [comment]
@dbader @kennethreitz 

Ready to go

**Pull request merged**
