### PR TITLE
added high_sierra setup instructions

### PR DESCRIPTION
**Pull request by bnorquist**

### CODE REVIEW

**Comment by kennethreitz** [comment]
`$ brew link python` i believe

**Comment by bnorquist** [comment]
that would link python 2 in the case where you have a user installed 2.7 as well though no?

**Comment by charliesneath** [comment]
@bnorquist Adding the following like to `PATH` fixed this issue for me:

`export PATH="~/Library/Python/3.6/bin"`

This fix is actually noted in the documentation in [this section's note](http://docs.python-guide.org/en/latest/dev/virtualenvs/#installing-pipenv), but it references `~/.local` as the typical output example, instead of the example above that is relevant to macOS users.

**Comment by cwfinn** [comment]
Not sure why this was closed. Following the instructions [here](http://docs.python-guide.org/en/latest/starting/install3/osx/) will not work as stated. It says, under the "Working with Python 3" section:

```
$ python
```
will launch the homebrew-installed Python 3 interpreter. But it will not under the instructions as they currently stand. It will launch the version of Python shipped with MacOS, since the stated path, `export PATH=/usr/local/bin:/usr/local/sbin:$PATH` is now incorrect, as stated and corrected for in this PR and the corresponding issue. Something needs to be added here, otherwise many people will become confused.

**Comment by jmmendivil** [comment]
> `$ brew link python` i believe

It's not the solution, see

```
$ brew link python
Warning: Already linked: /usr/local/Cellar/python/3.7.0
To relink: brew unlink python && brew link python
$ python --version
Python 2.7.10
```
the solution I found _(for a High Sierra clean install)_ is based on this _PR_. I too wonder why @kennethreitz closed this...

**Comment by bnorquist** [comment]
Just went through this again on a new computer. @kennethreitz `brew unlink python && brew link python` only works if you don't have a user installed python 2.7 
If you follow the instructions here: https://docs.python-guide.org/starting/install3/osx/ on High Sierra python will still point to system python 2.7

**Comment by dbader** [comment]
Hey so I'd love to get [the macOS install guide](https://docs.python-guide.org/starting/install3/osx/) updated so that the steps work correctly with a new Mojave install. 

Anybody here want to spin up a macOS VM & update the article?

**Comment by bnorquist** [comment]
@dbader I can probably do that this week. I'll link the PR here if it works out.

**Comment by bnorquist** [comment]
@dbader https://github.com/realpython/python-guide/pull/936
just tested these steps on a Mojave vm, works just fine.

**Pull request closed without merging**
