### PR TITLE
Add a Publishing Your Code section about GitHub

### LINKED ISSUE #803: Package your code to share it with other developers. ... github is missing
The "Packing your code" chapter starts like this: 

> Package your code to share it with other developers. 

From: http://docs.python-guide.org/en/latest/shipping/packaging/#packaging-your-code

The above sentence is true, if "other developers" means "users of your library".

If you want to share code with other people who want to modify and update your code, then Packaging is not the solution.

Maybe I am hair splitting here. Both groups of audience is very different. I think sharing code gets done via github, not via pypi.

I am missing a chapter about github. I think the live cycle of code looks like this:

IDE of developer -> Upload github (Pull request) -> CI OK? -> If CI ok, then merge into master -> upload to pypi.

### PR DESCRIPTION
**Pull request by apjanke**
Here's a first attempt at a section on hosting your project on GitHub.

It is opinionated, so it should fit right in. :)

Fixes #803.

### CODE REVIEW

**Comment by guettli** [comment]
I looked at it. Looks good. One small thing. I would change this:

> GitHub is currently the best.

I would write something like "most widespread" or "very common".

**Comment by guettli** [comment]
I like `pip install -e git+https://github.com/user/project.git#egg=project` since it is handy. Do you think this should be added?

**Comment by apjanke** [comment]
> > GitHub is currently the best.
>
> I would write something like "most widespread" or "very common".

I think we should go for "best". This guide is an opinionated set of recommendations, so I think this fits in.

I'll defer to the authors on whether GitHub actually is the best. But if we're recommending it, I think it should be on that basis, not just popularity.

> I like pip install -e git+https://github.com/user/project.git#egg=project since it is handy. Do you think this should be added?

I'm not familiar with that mechanism. I'll do some research.

**Comment by kenneth-reitz** [comment]
this looks great!

**Pull request merged**
